ci:
    autoupdate_schedule: quarterly

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-ast

  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [ -r, --in-place, --wrap-descriptions, '120', --wrap-summaries, '120', -- ]

  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.3
    hooks:
      - id: sign-commit
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0 # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: rst-directive-colons


  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [ --py37-plus ]

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.1
    hooks:
      - id: setup-cfg-fmt

  # Notebook formatting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-isort
        additional_dependencies: [ isort==5.6.4 ]
        args: [ --nbqa-mutate ]

      - id: nbqa-pyupgrade
        additional_dependencies: [ pyupgrade==2.7.4 ]
        args: [ --py37-plus, --nbqa-mutate]

  - repo: https://github.com/mgedmin/check-manifest
    rev: '0.48'
    hooks:
      - id: check-manifest
        stages: [ manual ]

  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: 'v1.0'  # Use the sha / tag you want to point at
    hooks:
      - id: upgrade-type-hints
        args: [ '--futures=true' ]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language: python

  - repo: https://github.com/roy-ht/pre-commit-jupyter
    rev: v1.2.1
    hooks:
      - id: jupyter-notebook-cleanup
  - repo: local
    hooks:
      - id: jupyter-notebook-rsync
        name: jupytersync
        entry: _website/sync_jupyter_notebooks.py
        language: system
        always_run: true
        additional_dependencies: [ sysrsync ]
