ci:
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-ast
      - id: end-of-file-fixer


  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0 # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: rst-directive-colons


  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args: [ --py38-plus ]

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
      - id: setup-cfg-fmt

  # Notebook formatting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-isort
        additional_dependencies: [ isort==5.6.4 ]

      - id: nbqa-pyupgrade
        additional_dependencies: [ pyupgrade==2.7.4 ]
        args: [ --py38-plus ]

  - repo: https://github.com/mgedmin/check-manifest
    rev: '0.50'
    hooks:
      - id: check-manifest
        stages: [ manual ]

  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: 'v1.0'
    hooks:
      - id: upgrade-type-hints

# TODO: requires Python 3.10+
#  - repo: https://github.com/janosh/format-ipy-cells
#    rev: v0.1.11
#    hooks:
#      - id: format-ipy-cells

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  - repo: local  # if this sync fails, make sure to add all, possibly new, notebooks to the sync script and run pre-commit with --all-files
    hooks:
      - id: jupyter-notebook-rsync
        name: jupytersync
        language: python
        entry: _website/sync_jupyter_notebooks.py
        always_run: true
