repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-ast

  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [ -r, --in-place, --wrap-descriptions, '120', --wrap-summaries, '120', -- ]

  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.3
    hooks:
      - id: sign-commit
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0 # Use the ref you want to point at
    hooks:
      - id: python-use-type-annotations
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: rst-directive-colons


  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.1
    hooks:
      - id: pyupgrade
        args: [ --py37-plus ]

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
      - id: setup-cfg-fmt

  # Notebook formatting
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.11.1
    hooks:
      - id: nbqa-isort
        additional_dependencies: [ isort==5.6.4 ]
        args: [ --nbqa-mutate ]

      - id: nbqa-pyupgrade
        additional_dependencies: [ pyupgrade==2.7.4 ]
        args: [ --py36-plus, --nbqa-mutate]

  - repo: https://github.com/mgedmin/check-manifest
    rev: '0.46'
    hooks:
      - id: check-manifest
        stages: [ manual ]

  - repo: https://github.com/sondrelg/pep585-upgrade
    rev: 'ab1595ee0aa8823dcda1f0bd95b2c194fcd5362b'  # Use the sha / tag you want to point at
    hooks:
      - id: upgrade-type-hints
        args: [ '--futures=true' ]

  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
        language: python
