name: zfit-tutorials
channels:
  - conda-forge
dependencies:
  - python=3.12
  - hepunits
  - matplotlib
  - numpy
  - numba
  - pandas
  - particle
  - pip
  - uv
  - scipy
  - xgboost
  - progressbar2
  - mplhep
  - hist
  - scikit-hep-testdata
  - hepstats
  - pip:
    - formulate
    - zfit >=0.14.1
    - zfit-physics
