name: zfit-tutorials
channels:
  - conda-forge
dependencies:
  - python=3.12
  - hepunits
  - matplotlib
  - numpy
  - numba
  - pandas
  - particle
  - pip
  - uv
  - scipy
  - xgboost
  - mplhep
  - hist
  - scikit-hep-testdata
  - hepstats
  - zfit >=0.26
  - zfit-physics
  - pip:
    - formulate
