name: zfit-tutorials
channels:
  - conda-forge
dependencies:
  - hepunits
  - matplotlib
  - numpy
  - numba
  - pandas
  - particle
  - pip
  - scipy
  - xgboost
  - progressbar2
  - mplhep
  - hist
  - rsync
  - sysrsync
  - pip:
    - zfit >=0.10
    - hepstats
    - formulate
