name: zfit-tutorials
channels:
  - conda-forge
dependencies:
  - hepunits
  - matplotlib
  - mplhep
  - numpy
  - numba
  - pandas
  - particle
  - pip
  - scipy
  - xgboost
  - progressbar2
  - mplhep
  - hist
  - pip:
    - zfit >=0.8,<0.10 --pre
    - hepstats
    - formulate
