name: zfit-tutorials
channels:
  - conda-forge
dependencies:
  - python=3.11
  - hepunits
  - matplotlib
  - numpy
  - numba
  - pandas
  - particle
  - pip
  - scipy
  - xgboost
  - progressbar2
  - mplhep
  - hist
  - scikit-hep-testdata
  - zfit >=0.14.1
  - zfit_physics
  - hepstats
  - pip:
    - formulate
